# Generated by Django 5.2.1 on 2025-07-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_planner', '0003_userimportantdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('icon', models.CharField(help_text='Font Awesome图标类名，如: fas fa-home', max_length=50, verbose_name='图标')),
                ('link', models.URLField(verbose_name='跳转链接')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('position', models.IntegerField(default=0, help_text='数字越小排序越靠前', verbose_name='位置序号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '便捷记录',
                'verbose_name_plural': '便捷记录',
                'ordering': ['position', '-created_at'],
            },
        ),
    ]
