# Generated by Django 5.2.1 on 2025-07-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_planner', '0004_quickaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickaccess',
            name='icon',
            field=models.ImageField(help_text='上传图标图片', upload_to='quick_access_icons/', verbose_name='图标'),
        ),
    ]
