# Generated by Django 5.2.1 on 2025-10-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_planner', '0005_alter_quickaccess_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('translation', models.CharField(max_length=30)),
                ('example_sentence', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '单词',
                'verbose_name_plural': '单词',
                'ordering': ['-created_at'],
            },
        ),
    ]
