# Generated by Django 5.2.1 on 2026-04-05 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_planner', '0008_daily_quotable_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimportantdate',
            name='planner_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='important_date_reminder', to='weekly_planner.task', verbose_name='关联周历任务'),
        ),
    ]
