# Generated by Django 4.2.14 on 2026-04-05 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weekly_planner', '0009_userimportantdate_planner_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantDatesHomeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='important_dates_home_snapshot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '首页重要日期快照',
                'verbose_name_plural': '首页重要日期快照',
            },
        ),
    ]
