# Generated by Django 4.2.14 on 2026-04-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_planner', '0010_important_dates_home_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalFamousQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='正文')),
                ('author', models.CharField(blank=True, default='', help_text='留空时首页显示为「佚名」。批量录入可设默认作者，或单行用「正文|作者」。', max_length=200, verbose_name='作者')),
                ('is_active', models.BooleanField(default=True, verbose_name='参与首页随机')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '本地名人名言',
                'verbose_name_plural': '本地名人名言',
                'ordering': ('-created_at',),
            },
        ),
    ]
