# Generated by Django 5.2.1 on 2026-04-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_planner', '0011_local_famous_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_unscheduled',
            field=models.BooleanField(default=False, help_text='为 True 时不显示在周历上，仅在「待安排」列表中，确定时间后排入日历', verbose_name='待安排'),
        ),
    ]
