# Generated by Django 4.2.14 on 2026-04-05 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weekly_planner', '0012_task_is_unscheduled'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepSeekProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, help_text='DeepSeek 控制台创建的 API Key', max_length=512, verbose_name='API Key')),
                ('api_base', models.URLField(default='https://api.deepseek.com', help_text='一般无需修改', verbose_name='API 基础地址')),
                ('default_model', models.CharField(default='deepseek-chat', max_length=100, verbose_name='默认模型')),
                ('request_timeout', models.PositiveIntegerField(default=120, help_text='周总结等长文本可适当增大', verbose_name='请求超时（秒）')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用 DeepSeek 调用')),
            ],
            options={
                'verbose_name': 'DeepSeek API 配置',
                'verbose_name_plural': 'DeepSeek API 配置',
            },
        ),
        migrations.CreateModel(
            name='WeeklyAiSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(db_index=True, help_text='home=全项目；subject:<项目id>=单项目', max_length=80, verbose_name='范围键')),
                ('week_start_date', models.DateField(db_index=True, verbose_name='周起始（周一）')),
                ('week_end_date', models.DateField(verbose_name='周结束（周日）')),
                ('title', models.CharField(blank=True, default='', max_length=300, verbose_name='标题')),
                ('overview', models.CharField(blank=True, default='', help_text='不超过约 50 字的短概述', max_length=200, verbose_name='概述')),
                ('body', models.TextField(blank=True, default='', help_text='AI 生成的周总结正文', verbose_name='详细')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '生成中'), ('completed', '已完成'), ('failed', '失败')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_ai_summaries', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '周智能总结',
                'verbose_name_plural': '周智能总结',
                'ordering': ('-week_start_date', '-created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='weeklyaisummary',
            constraint=models.UniqueConstraint(fields=('user', 'scope_key', 'week_start_date'), name='uniq_weekly_ai_summary_user_scope_week'),
        ),
    ]
