# Generated by Django 4.2.14 on 2026-04-05 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_planner', '0015_quickaccess_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickaccesslibraryicon',
            name='image',
            field=models.FileField(help_text='支持 PNG、SVG 等；栅格图须为 32×32 或 64×64 正方形，SVG 建议视口同尺寸。', upload_to='quick_access_library_icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'svg', 'jpg', 'jpeg', 'gif', 'webp'))], verbose_name='图标'),
        ),
    ]
