# Generated by Django 4.2.14 on 2026-04-05 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_planner', '0016_quickaccesslibraryicon_filefield_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickaccesslibraryicon',
            name='image',
            field=models.FileField(help_text='支持 PNG、SVG 等；栅格图须为正方形（宽高相等），SVG 建议视口为正方形。', upload_to='quick_access_library_icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'svg', 'jpg', 'jpeg', 'gif', 'webp'))], verbose_name='图标'),
        ),
    ]
