# Generated by Django 4.2.14 on 2026-04-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_weekly_dashboard_refreshed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weekly_dashboard_snapshot',
            field=models.JSONField(blank=True, help_text='点击「更新」时写入；首页只读此快照，避免每次打开首页全量聚合。', null=True, verbose_name='首页周统计快照'),
        ),
    ]
