# Generated by Django 5.2.1 on 2025-05-28 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20250527_1439'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePointAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='注释内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content_tag', models.PositiveIntegerField(help_text='注释关联的内容在知识点详细内容中的标签', verbose_name='内容标签')),
                ('content_length', models.PositiveIntegerField(default=0, help_text='注释关联的内容长度(字符数)', verbose_name='内容长度')),
                ('knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='courses.knowledgepoint', verbose_name='关联知识点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '知识点注释',
                'verbose_name_plural': '知识点注释',
                'ordering': ['created_at'],
                'unique_together': {('knowledge_point', 'content_tag')},
            },
        ),
    ]
