# Generated by Django 5.2.1 on 2025-05-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_knowledgepointannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepointannotation',
            name='quote',
            field=models.TextField(default='1', verbose_name='引用内容'),
            preserve_default=False,
        ),
    ]
