# Generated by Django 5.2.1 on 2025-05-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_knowledgepointannotation_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryLookupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=255, unique=True, verbose_name='查询文本')),
                ('src_text', models.TextField(verbose_name='源文本')),
                ('dst_text', models.TextField(verbose_name='目标文本')),
                ('src_tts', models.URLField(blank=True, null=True, verbose_name='源文本语音链接')),
                ('dst_tts', models.URLField(blank=True, null=True, verbose_name='目标文本语音链接')),
                ('dict_data', models.JSONField(blank=True, null=True, verbose_name='词典数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '词典查询记录',
                'verbose_name_plural': '词典查询记录',
            },
        ),
    ]
