# Generated by Django 5.2.1 on 2025-05-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_dictionarylookuprecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionarylookuprecord',
            name='dst_tts',
        ),
        migrations.RemoveField(
            model_name='dictionarylookuprecord',
            name='src_tts',
        ),
        migrations.AddField(
            model_name='dictionarylookuprecord',
            name='dst_audio',
            field=models.FileField(blank=True, null=True, upload_to='tts/zh/', verbose_name='目标语音文件'),
        ),
        migrations.AddField(
            model_name='dictionarylookuprecord',
            name='dst_tts_url',
            field=models.URLField(blank=True, null=True, verbose_name='目标语音URL'),
        ),
        migrations.AddField(
            model_name='dictionarylookuprecord',
            name='src_audio',
            field=models.FileField(blank=True, null=True, upload_to='tts/en/', verbose_name='源语音文件'),
        ),
        migrations.AddField(
            model_name='dictionarylookuprecord',
            name='src_tts_url',
            field=models.URLField(blank=True, null=True, verbose_name='源语音URL'),
        ),
    ]
