# Generated by Django 5.2.1 on 2025-06-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_dictionarylookuprecord_dst_tts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='process_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='进度描述'),
        ),
    ]
