# Generated by Django 5.2.1 on 2025-06-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_chapter_process_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Chapters_count',
            field=models.PositiveIntegerField(default=0, verbose_name='章节总数'),
        ),
    ]
