# Generated by Django 5.2.1 on 2025-06-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_subject_chapters_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='学习进度，0-100之间', verbose_name='学习进度(%)'),
        ),
    ]
