# Generated by Django 5.2.1 on 2025-06-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_subject_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='estimated_hours',
            field=models.PositiveIntegerField(default=1, verbose_name='预计学时(小时)'),
        ),
    ]
