# Generated by Django 5.2.1 on 2025-06-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_subject_estimated_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='estimated_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='预计学时(小时)'),
        ),
    ]
