# Generated by Django 5.2.1 on 2025-07-02 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_subject_estimated_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgepoint',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='related_knowledge_points', to='courses.exercise', verbose_name='关联习题'),
        ),
        migrations.CreateModel(
            name='ExerciseKnowledgePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关联时间')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序序号')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.exercise', verbose_name='习题')),
                ('knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.knowledgepoint', verbose_name='知识点')),
            ],
            options={
                'verbose_name': '习题知识点关联',
                'verbose_name_plural': '习题知识点关联',
                'ordering': ['exercise', 'order'],
                'unique_together': {('exercise', 'knowledge_point')},
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='knowledge_points',
            field=models.ManyToManyField(blank=True, related_name='related_exercises', through='courses.ExerciseKnowledgePoint', through_fields=('exercise', 'knowledge_point'), to='courses.knowledgepoint', verbose_name='关联知识点'),
        ),
    ]
