# Generated by Django 5.2.1 on 2025-07-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_knowledgepoint_exercises_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='correct_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='正确次数'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='wrong_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='错误次数'),
        ),
    ]
