# Generated by Django 5.2.1 on 2025-08-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_exercise_correct_count_alter_exercise_wrong_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodsummary',
            name='chapter_title',
            field=models.CharField(blank=True, help_text='如果章节已删除或不存在，则此字段用于显示章节标题', max_length=100, null=True, verbose_name='章节标题'),
        ),
    ]
