# Generated by Django 5.2.1 on 2025-10-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_methodsummary_chapter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodsummary',
            name='knowledgePoint',
            field=models.ManyToManyField(to='courses.knowledgepoint', verbose_name='关联知识点'),
        ),
    ]
