# Generated by Django 5.2.1 on 2025-10-24 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_methodsummary_knowledgepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodsummary',
            name='difficulty_level',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='难度'),
        ),
        migrations.AddField(
            model_name='methodsummary',
            name='improtant_level',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='重要度'),
        ),
    ]
