# Generated by Django 5.2.1 on 2025-10-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_methodsummary_difficulty_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='methodsummary',
            old_name='improtant_level',
            new_name='important_level',
        ),
    ]
