# Generated by Django 5.2.1 on 2026-03-21 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_rename_improtant_level_methodsummary_important_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='科目分类名称')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('display_weight', models.IntegerField(default=0, help_text='数值越大，在项目列表中越靠前展示', verbose_name='显示权重')),
            ],
            options={
                'verbose_name': '科目分类',
                'verbose_name_plural': '科目分类',
                'ordering': ['-display_weight', 'id'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='courses.subjectcategory', verbose_name='科目分类'),
        ),
    ]
