# Generated by Django 4.2.14 on 2026-04-05 02:31

from django.db import migrations, models


VALID = frozenset({"进行中", "攻坚", "收尾", "挂起", "完成"})


def copy_process_to_status(apps, schema_editor):
    Chapter = apps.get_model("courses", "Chapter")
    for ch in Chapter.objects.all():
        old = (getattr(ch, "process_description", None) or "").strip()
        ch.progress_status = old if old in VALID else "进行中"
        ch.save(update_fields=["progress_status"])


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0021_subject_already_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="progress_status",
            field=models.CharField(
                choices=[
                    ("进行中", "进行中"),
                    ("攻坚", "攻坚"),
                    ("收尾", "收尾"),
                    ("挂起", "挂起"),
                    ("完成", "完成"),
                ],
                default="进行中",
                max_length=20,
                verbose_name="进度状态",
            ),
        ),
        migrations.RunPython(copy_process_to_status, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="chapter",
            name="process_description",
        ),
    ]
