# Generated by Django 4.2.14 on 2026-04-05 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0022_chapter_progress_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectPlanSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('overview', models.TextField(blank=True, verbose_name='概述')),
                ('body', models.TextField(blank=True, help_text='AiEditor 等保存的 HTML', verbose_name='正文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_summaries', to='courses.subject', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_plan_summaries', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目总结',
                'verbose_name_plural': '项目总结',
                'ordering': ['-created_at'],
            },
        ),
    ]
