# Generated by Django 4.2.14 on 2026-04-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_subject_plan_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseanswer',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exerciseanswer',
            name='exercise_set_completion',
        ),
        migrations.RemoveField(
            model_name='exerciseanswer',
            name='review_set_completion',
        ),
        migrations.RemoveField(
            model_name='exerciseanswer',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='exerciseknowledgepoint',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='exerciseknowledgepoint',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exerciseknowledgepoint',
            name='knowledge_point',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='exercisesetcompletion',
            name='exercise_set',
        ),
        migrations.RemoveField(
            model_name='exercisesetcompletion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewset',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='reviewset',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='reviewsetcompletion',
            name='review_set',
        ),
        migrations.RemoveField(
            model_name='reviewsetcompletion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='knowledgepoint',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='methodsummary',
            name='exercises',
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('videos', '视频评论'), ('documents', '文档评论'), ('knowledge_points', '知识点评论'), ('chapter', '章节评论'), ('smart-review', '复习任务评论'), ('other', '其他')], default='other', max_length=20, verbose_name='评论类型'),
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='ExerciseAnswer',
        ),
        migrations.DeleteModel(
            name='ExerciseKnowledgePoint',
        ),
        migrations.DeleteModel(
            name='ExerciseSet',
        ),
        migrations.DeleteModel(
            name='ExerciseSetCompletion',
        ),
        migrations.DeleteModel(
            name='ReviewSet',
        ),
        migrations.DeleteModel(
            name='ReviewSetCompletion',
        ),
    ]
