# Generated by Django 5.2.1 on 2026-07-29 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_remove_exercise_and_review_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectHeatTracker',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('creations_since_decay', models.PositiveIntegerField(default=0, verbose_name='距上次衰减的创建次数')),
            ],
            options={
                'verbose_name': '项目热度计数器',
                'verbose_name_plural': '项目热度计数器',
            },
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-heat', 'order', 'name'], 'verbose_name': '科目', 'verbose_name_plural': '科目'},
        ),
        migrations.AddField(
            model_name='subject',
            name='heat',
            field=models.PositiveSmallIntegerField(default=0, help_text='0–10，用于日历/记录里项目下拉排序；创建周历任务时会自动调整', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='项目热度'),
        ),
    ]
