# Generated by Django 5.2.1 on 2026-07-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_subject_heat'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='open_status',
            field=models.CharField(choices=[('open', '开启'), ('closed', '关闭')], db_index=True, default='open', help_text='关闭后的项目不出现在主列表与日历/记录选项目下拉中', max_length=16, verbose_name='项目状态'),
        ),
    ]
