# Generated by Django 4.2.14 on 2026-08-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_subject_open_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='hist_actual_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='历史已投入时长(小时)'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='hist_plan_task_count',
            field=models.PositiveIntegerField(default=0, help_text='各周写入总结时累加的计划子任务数', verbose_name='历史子任务数量'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='hist_planned_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='历史计划投入时长(小时)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='hist_stats_rolled_week_start',
            field=models.DateField(blank=True, help_text='最近一次把本周统计写入各任务历史字段时的周一日期；同周重复插入总结不会重复累加', null=True, verbose_name='历史统计已累加周起始'),
        ),
    ]
