# Generated by Django 4.2.14 on 2026-08-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_chapter_hist_plan_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='last_roll_actual_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最近一周累加的已投入时长'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='last_roll_plan_task_count',
            field=models.PositiveIntegerField(default=0, verbose_name='最近一周累加的子任务数'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='last_roll_planned_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最近一周累加的计划时长'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='last_roll_week_start',
            field=models.DateField(blank=True, null=True, verbose_name='最近累加的周起始'),
        ),
    ]
